version: '3.8'

services:
  backend:
    build:
      dockerfile: ./Dockerfile.dev
    restart: unless-stopped
    ports:
      - 4000:4000
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:7.0-alpine3.16
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'

volumes:
  db_data:
  redis-data:
